/* This file was generated by the Hex-Rays decompiler version 7.7.0.220118.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __cdecl __noreturn j_exit(int Code);
__int64 __fastcall sub_1400112A3(_QWORD, _QWORD); // weak
__int64 __fastcall sub_1400112D5(_QWORD); // weak
int __cdecl j__initterm_e(_PIFV *First, _PIFV *Last);
__int64 __fastcall start(); // weak
__int64 sub_14001151E(void); // weak
__int64 sub_140011532(void); // weak
__int64 sub_140011550(void); // weak
__int64 sub_14001159B(void); // weak
__int64 __fastcall sub_1400115F0(_QWORD); // weak
__int64 __fastcall sub_14001160E(_QWORD); // weak
void __cdecl j__initterm(_PVFV *First, _PVFV *Last);
__int64 sub_140011654(void); // weak
void __cdecl j__register_thread_local_exe_atexit_callback(_tls_callback_type Callback);
void __cdecl j__cexit();
__int64 __fastcall sub_14001175D(_QWORD); // weak
__int64 sub_1400295C0();
__int64 sub_1400295E0();
__int64 sub_140029830(void); // weak
__int64 start_0();
// void __cdecl __noreturn exit(int Code);


//----- (00000001400298F0) ----------------------------------------------------
__int64 start_0()
{
  return sub_1400295C0();
}
// 1400295C0: using guessed type __int64 sub_1400295C0(void);

// nfuncs=811 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
