/* This file was generated by the Hex-Rays decompiler version 7.7.0.220118.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int sub_140001000();
int sub_140001030();
int sub_1400015E0();
int sub_1400016A0();
int sub_1400016F4();
// __int64 __fastcall unknown_libname_17(_QWORD, _QWORD); weak
// __int64 __fastcall std::exception::exception(std::exception *__hidden this, const char *const, int); idb
_QWORD *__fastcall sub_140001760(_QWORD *a1, __int64 a2);
__int64 __fastcall sub_1400017C0(_QWORD *a1);
_QWORD *__fastcall sub_140001830(_QWORD *a1, char a2);
_QWORD *__fastcall sub_1400018B0(_QWORD *a1, char a2);
__int64 __fastcall sub_1400018F0(_QWORD *a1);
// __int64 __fastcall std::bad_array_new_length::bad_array_new_length(std::bad_array_new_length *__hidden this); idb
_QWORD *__fastcall sub_140001950(_QWORD *a1, char a2);
__int64 __fastcall sub_140001990(_QWORD *a1);
void __fastcall __noreturn sub_1400019B0(_QWORD, _QWORD); // weak
_QWORD *__fastcall sub_1400019E0(_QWORD *a1, __int64 a2);
_QWORD *__fastcall sub_140001A20(_QWORD *a1, __int64 a2);
void *__fastcall sub_140001A70(size_t a1);
_QWORD *__fastcall sub_140001A90(_QWORD *a1, _QWORD *a2);
void sub_140001B30();
// void __fastcall __crt_win32_buffer_no_resizing::deallocate(void *const, const struct __crt_win32_buffer_empty_debug_info *); idb
// __int64 __fastcall std::_Fake_proxy_ptr_impl::_Fake_proxy_ptr_impl(std::_Fake_proxy_ptr_impl *__hidden this, const struct std::_Fake_allocator *, const struct std::_Container_base0 *); idb
void __noreturn sub_140001B70(void); // weak
std::exception *__fastcall sub_140001B90(std::exception *a1);
void __noreturn sub_140001BD0(void); // weak
_QWORD *__fastcall sub_140001C00(_QWORD *a1, __int64 a2);
__int64 (__fastcall ***__fastcall sub_140001C40(__int64 a1))(_QWORD, __int64);
__int64 __fastcall sub_140001CB0(__int64 a1, unsigned __int64 a2);
__int64 __fastcall sub_140001D60(void *a1, unsigned __int64 a2);
__int64 sub_140001D80();
__int64 sub_140001DB0();
int __cdecl main(int argc, const char **argv, const char **envp);
// __int64 __fastcall std::u16string_view::basic_string_view<char16_t,std::char_traits<char16_t>>(_QWORD, _QWORD, _QWORD); weak
__int64 __fastcall sub_140002130(_QWORD *a1, __int64 a2);
__int64 __fastcall sub_140002160(_QWORD *a1);
__int64 *__fastcall sub_140002190(__int64 *a1);
__int64 __fastcall sub_1400021B0(__int64 a1, __FrameHandler3::TryBlockMap *a2, __int64 a3);
__int64 __fastcall sub_140002230(__int64 a1, unsigned __int64 a2, const void *a3, __int64 a4);
// __int64 __fastcall unknown_libname_18(_QWORD); weak
// __int64 __fastcall unknown_libname_19(_QWORD); weak
__int64 __fastcall sub_1400022A0(__int64 a1, __int64 a2);
// __int64 __fastcall std::string::~string(_QWORD); weak
void *__fastcall sub_140002300(void *a1);
void sub_140002350();
void sub_140002370();
__int64 __fastcall sub_140002390(_QWORD *a1);
// struct _xDISPATCHER_CONTEXT *__fastcall __FrameHandler3::TryBlockMap::getpDC(__FrameHandler3::TryBlockMap *__hidden this); idb
// __int64 __fastcall unknown_libname_20(_QWORD); weak
__int64 *__fastcall sub_1400023D0(__int64 *a1);
__int64 __fastcall sub_1400024A0(__int64 a1);
__int64 __fastcall sub_140002580(__int64 a1);
_QWORD *__fastcall sub_1400025E0(_QWORD *a1, char a2);
__int64 sub_1400026B0(__int64 a1, char *a2, const void *a3, unsigned __int64 a4, ...);
// __int64 __fastcall unknown_libname_7(_QWORD); weak
__int64 sub_140002760();
// __int64 __fastcall unknown_libname_8(_QWORD, _QWORD); weak
// __int64 __fastcall std::_Atomic_reinterpret_as<char,char>(_QWORD); weak
// __int64 __fastcall unknown_libname_9(_QWORD); weak
void *__fastcall sub_140002800(void *a1, const void *a2, unsigned __int64 a3);
__int64 __fastcall sub_140002830(__int64 a1, __int64 a2, __int64 a3);
// __int64 __fastcall unknown_libname_10(_QWORD, _QWORD); weak
__int64 __fastcall sub_1400028B0(__int64 a1, __int64 a2);
// __int64 __fastcall std::string::shrink_to_fit(_QWORD); weak
// __int64 __fastcall std::allocator<char>::allocate(_QWORD, _QWORD); weak
// __int64 __fastcall std::allocator<char>::deallocate(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall unknown_libname_11(_QWORD, _QWORD); weak
void __fastcall sub_140002A40(__int64 a1, unsigned __int64 a2);
void sub_140002A80();
__int64 __fastcall sub_140002AA0(__int64 a1);
__int64 __fastcall sub_140002BE0(__int64 a1, __int64 a2);
__int64 __fastcall sub_140002FB0(__int64 a1, _QWORD *a2);
__int64 __fastcall sub_140003310(__int64 a1, __int64 a2, __int64 a3);
void __fastcall sub_140003350(__int64 a1, unsigned __int64 a2, __int64 a3, __int64 a4);
void __fastcall sub_140003450(__int64 a1, unsigned __int64 a2, const void *a3);
__int64 __fastcall sub_140003570(__int64 a1);
// __int64 __fastcall _castguard_slow_path_check_nop(_QWORD, _QWORD, _QWORD); weak
_QWORD *__fastcall sub_1400035B0(_QWORD *a1, unsigned __int64 a2, char a3, char a4);
__int64 __fastcall sub_140003790(__int64 a1, __int64 a2);
// __int64 __fastcall std::_Deallocate<16,0>(_QWORD, _QWORD); weak
// __int64 __fastcall std::_Allocate<16,std::_Default_allocate_traits,0>(_QWORD); weak
__int64 __fastcall sub_140003880(__int64 a1);
__int64 *__fastcall sub_1400038A0(__int64 **a1);
// __int64 __fastcall std::optional<unsigned __int64>::operator bool(_QWORD); weak
__int64 __fastcall sub_1400038E0(__int64 a1, __int64 a2, unsigned __int8 a3);
__int64 __fastcall sub_140003930(__int64 a1);
__int64 __fastcall sub_140003990(_QWORD *a1);
__int64 __fastcall sub_1400039F0(__int64 a1, __int64 a2);
__int64 __fastcall sub_140003AD0(__int64 a1);
__int64 __fastcall sub_140003B00(__int64 (__fastcall ****a1)(_QWORD, __int64));
// __int64 __fastcall unknown_libname_21(_QWORD); weak
unsigned __int64 __fastcall sub_140003B80(__int64 *a1, unsigned __int64 a2);
unsigned __int64 __fastcall sub_140003BC0(__int64 a1, __int64 a2);
__int64 __fastcall sub_140003C00(__int64 a1, unsigned __int64 a2);
__int64 __fastcall sub_140003C40(__int64 a1);
__int64 __fastcall sub_140003C80(__int64 a1, __int64 a2);
__int64 __fastcall sub_140003CF0(__int64 a1, __int64 (__fastcall ***a2)(_QWORD, __int64));
void __noreturn sub_140003D40(void); // weak
unsigned __int64 __fastcall sub_140003D60(__int64 *a1, unsigned __int64 a2);
// __int64 __fastcall std::_Tree<std::_Tmap_traits<void *,`anonymous namespace'::_Mutex_count_pair,std::less<void *>,std::_Crt_allocator<std::pair<void * const,`anonymous namespace'::_Mutex_count_pair>>,0>>::max_size(_QWORD); weak
unsigned __int64 __fastcall sub_140003E40(__int64 a1, unsigned __int64 a2, unsigned __int64 a3);
// __int64 __fastcall unknown_libname_22(_QWORD); weak
__int64 __fastcall sub_140003F10(); // weak
__int64 __fastcall sub_140003F20(__int64 a1, unsigned __int64 a2);
// __int64 __fastcall std::_Unique_ptr_base<std::_Facet_base,std::default_delete<std::_Facet_base>>::_Unique_ptr_base<std::_Facet_base,std::default_delete<std::_Facet_base>>(_QWORD, _QWORD); weak
__int64 __fastcall sub_140003F80(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall sub_1400040A0(__int64 a1, __int64 a2, const void *a3, __int64 a4);
unsigned __int64 __fastcall sub_140004180(unsigned __int64 a1, __int64 a2);
// __int64 __fastcall unknown_libname_15(_QWORD, _QWORD); weak
__int64 __fastcall sub_140004250(unsigned __int64 a1, __int64 a2);
__int64 __fastcall sub_1400042A0(_QWORD *a1);
__int64 __fastcall sub_1400042C0(_QWORD *a1);
_QWORD *__fastcall sub_1400042F0(_QWORD *a1, __int64 a2, __int64 a3);
_QWORD *__fastcall sub_140004330(_QWORD *a1, __int64 a2, __int64 a3);
char *__fastcall sub_140004370(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_140004410(__int64 a1, __int64 a2);
_BOOL8 __fastcall sub_140004470(const void *a1);
__int64 __fastcall sub_1400044E0(__int64 a1, __int64 a2);
__int64 __fastcall sub_140004520(__int64 a1, __int64 a2, __int64 a3);
// void __fastcall std::_Facet_Register(struct std::_Facet_base *); idb
// void *__fastcall operator new(size_t Size); idb
// int __cdecl atexit(void (__cdecl *)());
void __cdecl j_j_free(void *Block);
_QWORD *__fastcall sub_140004864(_QWORD *a1, char a2);
_QWORD *__fastcall sub_140004C84(_QWORD *a1);
void __fastcall __noreturn sub_140004CA4(); // weak
void __fastcall __noreturn sub_140004CC4(); // weak
__int64 __fastcall sub_140004CE4(); // weak
void sub_140004EA4();
__int64 __fastcall UserMathErrorFunction(struct _exception *a1);
bool sub_140005004();
void sub_140005180();
char sub_140005190();
void *sub_140005194();
void *sub_14000519C();
void *sub_1400051CC();
void *sub_1400051D4();
void sub_1400051DC();
void __fastcall sub_140005218();
// void __stdcall __noreturn CxxThrowException(void *pExceptionObject, _ThrowInfo *pThrowInfo);
// int __cdecl memcmp(const void *Buf1, const void *Buf2, size_t Size);
// void *__cdecl memmove(void *, const void *Src, size_t Size);
void __fastcall sub_140005690();
void __fastcall sub_1400056B0();
void __fastcall sub_1400056D0();
void __fastcall sub_1400056F0();
// __int64 __fastcall unknown_libname_16(); weak
// __int64 __fastcall std::ios::fill(_QWORD); weak
// __int64 __fastcall std::streambuf::sgetc(_QWORD); weak
// __int64 __fastcall std::streambuf::sputc(_QWORD, _QWORD); weak
// __int64 __fastcall std::ios_base::getloc(_QWORD, _QWORD); weak
// __int64 __fastcall std::ios_base::width(std::ios_base *__hidden this, __int64); weak
// __int64 __fastcall std::ios::setstate(_QWORD, _QWORD, _QWORD); weak
// _DWORD std::ios_base::flags(std::ios_base *__hidden this); weak
// bool std::ios_base::good(std::ios_base *__hidden this); weak
// __int64 __fastcall std::ctype<char>::_Getcat(_QWORD, _QWORD); weak
// __int64 __fastcall std::ctype<char>::is(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall std::locale::id::operator unsigned __int64(_QWORD); weak
// __int64 __fastcall std::streambuf::sputn(_QWORD, _QWORD, _QWORD); weak
// void std::_Lockit::~_Lockit(std::_Lockit *__hidden this); weak
// __int64 __fastcall std::streambuf::snextc(_QWORD); weak
// __int64 __fastcall std::istream::_Ipfx(_QWORD, _QWORD); weak
// __int64 __fastcall std::ostream::flush(_QWORD); weak
// __int64 __fastcall std::ostream::_Osfx(_QWORD); weak
// __int64 __fastcall std::ios::tie(_QWORD); weak
// void __fastcall __noreturn std::_Xlength_error(const char *); weak
// void __fastcall std::_Xout_of_range(const char *); weak
// bool std::uncaught_exception(void); weak
// __int64 __fastcall std::ios::rdbuf(_QWORD); weak
// __int64 std::locale::_Getgloballocale(void); weak
// _QWORD __fastcall std::_Lockit::_Lockit(std::_Lockit *__hidden this, _DWORD); weak
// __int64 std::ios_base::width(std::ios_base *__hidden this); weak
// __int64 __fastcall _std_exception_copy(_QWORD, _QWORD); weak
// __int64 __fastcall _std_exception_destroy(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern HMODULE (__stdcall *GetModuleHandleW)(LPCWSTR lpModuleName);
// extern _UNKNOWN std::ctype<char>::id; weak
// extern _UNKNOWN std::cin; weak
// extern _UNKNOWN std::cout; weak
// extern void (__cdecl __noreturn *invalid_parameter_noinfo_noreturn)();
void *type_info::`vftable' = &sub_140004864; // weak
void *std::exception::`vftable' = &sub_140001830; // weak
void *std::bad_alloc::`vftable' = &sub_1400018B0; // weak
void *std::bad_array_new_length::`vftable' = &sub_140001950; // weak
_UNKNOWN unk_140006471; // weak
void *std::bad_cast::`vftable' = &sub_1400018B0; // weak
void (*qword_140006D70[2])(void) = { NULL, NULL }; // weak
void (*qword_140006D80)(void) = NULL; // weak
const _ThrowInfo _TI2_AVbad_alloc_std__ = { 0u, 6384, 0, 29136 }; // idb
const _ThrowInfo _TI2_AVbad_cast_std__ = { 0u, 6384, 0, 29192 }; // idb
const _ThrowInfo _TI3_AVbad_array_new_length_std__ = { 0u, 6544, 0, 29160 }; // idb
int dword_140009018 = 1; // weak
int dword_14000901C = 2; // weak
__int64 qword_140009020 = 524288i64; // weak
__int64 qword_140009028 = 33554432i64; // weak
int dword_1400096E0; // weak
int dword_1400096E4; // weak
union _SLIST_HEADER stru_1400096F0; // weak
_UNKNOWN unk_140009700; // weak
_UNKNOWN unk_140009708; // weak
__int64 input_2; // weak
__int64 qword_140009718[3]; // weak
_QWORD input_1[3]; // weak
__int64 qword_140009748[3]; // weak
_UNKNOWN password; // weak
char byte_140009780; // weak
__int64 qword_140009788; // weak
_UNKNOWN unk_140009790; // weak
_UNKNOWN unk_140009798; // weak


//----- (0000000140001000) ----------------------------------------------------
int sub_140001000()
{
  sub_140002300(&password);
  return atexit(sub_140005690);
}

//----- (0000000140001030) ----------------------------------------------------
int sub_140001030()
{
  __int64 v0; // rax
  char v2[16]; // [rsp+20h] [rbp-248h] BYREF
  int v3[125]; // [rsp+30h] [rbp-238h] BYREF
  char v4[12]; // [rsp+224h] [rbp-44h] BYREF
  char v5[16]; // [rsp+230h] [rbp-38h] BYREF
  char v6[40]; // [rsp+240h] [rbp-28h] BYREF

  sub_140001D60(input_1, 0x18ui64);
  v3[0] = 2;
  v3[1] = 1;
  v3[2] = 0;
  v3[3] = 1;
  v3[4] = 2;
  v3[5] = 0;
  v3[6] = 3;
  v3[7] = 1;
  v3[8] = 2;
  v3[9] = 1;
  v3[10] = 2;
  v3[11] = 1;
  v3[12] = 4;
  v3[13] = 1;
  v3[14] = 2;
  v3[15] = 6;
  v3[16] = 102;
  v3[17] = 2;
  v3[18] = 1;
  v3[19] = 1;
  v3[20] = 3;
  v3[21] = 2;
  v3[22] = 1;
  v3[23] = 1;
  v3[24] = 3;
  v3[25] = 2;
  v3[26] = 4;
  v3[27] = 2;
  v3[28] = 3;
  v3[29] = 6;
  v3[30] = 88;
  v3[31] = 2;
  v3[32] = 2;
  v3[33] = 2;
  v3[34] = 1;
  v3[35] = 1;
  v3[36] = 3;
  v3[37] = 4;
  v3[38] = 2;
  v3[39] = 1;
  v3[40] = 6;
  v3[41] = 77;
  v3[42] = 2;
  v3[43] = 1;
  v3[44] = 3;
  v3[45] = 2;
  v3[46] = 2;
  v3[47] = 4;
  v3[48] = 2;
  v3[49] = 3;
  v3[50] = 5;
  v3[51] = 2;
  v3[52] = 4;
  v3[53] = 6;
  v3[54] = 1;
  v3[55] = 0;
  v3[56] = 4;
  v3[57] = 4;
  v3[58] = 1;
  v3[59] = 0;
  v3[60] = 6;
  v3[61] = 57;
  v3[62] = 1;
  v3[63] = 0;
  v3[64] = 5;
  v3[65] = 3;
  v3[66] = 1;
  v3[67] = 2;
  v3[68] = 3;
  v3[69] = 1;
  v3[70] = 4;
  v3[71] = 4;
  v3[72] = 0;
  v3[73] = 1;
  v3[74] = 6;
  v3[75] = 43;
  v3[76] = 2;
  v3[77] = 4;
  v3[78] = 6;
  v3[79] = 3;
  v3[80] = 3;
  v3[81] = 4;
  v3[82] = 1;
  v3[83] = 4;
  v3[84] = 6;
  v3[85] = 4;
  v3[86] = 3;
  v3[87] = 4;
  v3[88] = 6;
  v3[89] = 29;
  v3[90] = 2;
  v3[91] = 1;
  v3[92] = 3;
  v3[93] = 2;
  v3[94] = 2;
  v3[95] = 4;
  v3[96] = 2;
  v3[97] = 3;
  v3[98] = 5;
  v3[99] = 2;
  v3[100] = 4;
  v3[101] = 6;
  v3[102] = 3;
  v3[103] = 4;
  v3[104] = 1;
  v3[105] = 3;
  v3[106] = 4;
  v3[107] = 2;
  v3[108] = 3;
  v3[109] = 4;
  v3[110] = 3;
  v3[111] = 1;
  v3[112] = 1;
  v3[113] = 7;
  v3[114] = 4;
  v3[115] = 4;
  v3[116] = 1;
  v3[117] = 5;
  v3[118] = 1;
  v3[119] = 8;
  v3[120] = 9;
  v3[121] = 7;
  v3[122] = 6;
  v3[123] = -5;
  v3[124] = 7;
  qmemcpy(
    v5,
    (const void *)std::u16string_view::basic_string_view<char16_t,std::char_traits<char16_t>>(v6, v3, v4),
    sizeof(v5));
  v0 = unknown_libname_18(v2);
  sub_1400021B0((__int64)input_1, (__FrameHandler3::TryBlockMap *)v5, v0);
  return atexit(sub_1400056B0);
}
// 140002100: using guessed type __int64 __fastcall std::u16string_view::basic_string_view<char16_t,std::char_traits<char16_t>>(_QWORD, _QWORD, _QWORD);
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 140009730: using guessed type _QWORD input_1[3];
// 140001030: using guessed type char var_44[12];
// 140001030: using guessed type char var_28[40];
// 140001030: using guessed type char var_248[16];

//----- (00000001400015E0) ----------------------------------------------------
int sub_1400015E0()
{
  __int64 v0; // rax
  char v2[16]; // [rsp+20h] [rbp-78h] BYREF
  char v3[16]; // [rsp+30h] [rbp-68h] BYREF
  char v4[16]; // [rsp+40h] [rbp-58h] BYREF
  int v5[8]; // [rsp+50h] [rbp-48h] BYREF
  char v6[40]; // [rsp+70h] [rbp-28h] BYREF

  sub_140001D60(qword_140009748, 0x18ui64);
  v5[0] = 77;
  v5[1] = 4;
  v5[2] = 73;
  v5[3] = 95;
  v5[4] = 71;
  v5[5] = 76;
  v5[6] = 11;
  v5[7] = 3;
  qmemcpy(
    v3,
    (const void *)std::u16string_view::basic_string_view<char16_t,std::char_traits<char16_t>>(v4, v5, v6),
    sizeof(v3));
  v0 = unknown_libname_18(v2);
  sub_1400021B0((__int64)qword_140009748, (__FrameHandler3::TryBlockMap *)v3, v0);
  return atexit(sub_1400056D0);
}
// 140002100: using guessed type __int64 __fastcall std::u16string_view::basic_string_view<char16_t,std::char_traits<char16_t>>(_QWORD, _QWORD, _QWORD);
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 140009748: using guessed type __int64 qword_140009748[3];
// 1400015E0: using guessed type char var_28[40];
// 1400015E0: using guessed type char var_58[16];
// 1400015E0: using guessed type char var_78[16];

//----- (00000001400016A0) ----------------------------------------------------
int sub_1400016A0()
{
  __int64 v0; // rax
  char v2[4]; // [rsp+20h] [rbp-18h] BYREF
  int v3[5]; // [rsp+24h] [rbp-14h] BYREF

  sub_140001D60(qword_140009718, 0x18ui64);
  v3[0] = 0;
  v0 = unknown_libname_18(v2);
  sub_140002230((__int64)qword_140009718, 0x64ui64, v3, v0);
  return atexit(sub_1400056F0);
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 140009718: using guessed type __int64 qword_140009718[3];
// 1400016A0: using guessed type int var_14[5];
// 1400016A0: using guessed type char var_18[4];

//----- (00000001400016F4) ----------------------------------------------------
int sub_1400016F4()
{
  return atexit((void (__cdecl *)())unknown_libname_16);
}
// 140005708: using guessed type __int64 __fastcall unknown_libname_16();

//----- (0000000140001760) ----------------------------------------------------
_QWORD *__fastcall sub_140001760(_QWORD *a1, __int64 a2)
{
  *a1 = &std::exception::`vftable';
  memset(a1 + 1, 0, 0x10ui64);
  _std_exception_copy(a2 + 8, a1 + 1);
  return a1;
}
// 140006198: using guessed type __int64 __fastcall _std_exception_copy(_QWORD, _QWORD);
// 1400063C8: using guessed type void *std::exception::`vftable';

//----- (00000001400017C0) ----------------------------------------------------
__int64 __fastcall sub_1400017C0(_QWORD *a1)
{
  *a1 = &std::exception::`vftable';
  return _std_exception_destroy(a1 + 1);
}
// 1400061A0: using guessed type __int64 __fastcall _std_exception_destroy(_QWORD);
// 1400063C8: using guessed type void *std::exception::`vftable';

//----- (0000000140001830) ----------------------------------------------------
_QWORD *__fastcall sub_140001830(_QWORD *a1, char a2)
{
  sub_1400017C0(a1);
  if ( (a2 & 1) != 0 )
    j_j_free(a1);
  return a1;
}

//----- (00000001400018B0) ----------------------------------------------------
_QWORD *__fastcall sub_1400018B0(_QWORD *a1, char a2)
{
  sub_1400018F0(a1);
  if ( (a2 & 1) != 0 )
    j_j_free(a1);
  return a1;
}

//----- (00000001400018F0) ----------------------------------------------------
__int64 __fastcall sub_1400018F0(_QWORD *a1)
{
  return sub_1400017C0(a1);
}

//----- (0000000140001950) ----------------------------------------------------
_QWORD *__fastcall sub_140001950(_QWORD *a1, char a2)
{
  sub_140001990(a1);
  if ( (a2 & 1) != 0 )
    j_j_free(a1);
  return a1;
}

//----- (0000000140001990) ----------------------------------------------------
__int64 __fastcall sub_140001990(_QWORD *a1)
{
  return sub_1400018F0(a1);
}

//----- (00000001400019B0) ----------------------------------------------------
void __noreturn sub_1400019B0()
{
  char pExceptionObject[40]; // [rsp+20h] [rbp-28h] BYREF

  std::bad_array_new_length::bad_array_new_length((std::bad_array_new_length *)pExceptionObject);
  CxxThrowException(pExceptionObject, (_ThrowInfo *)&_TI3_AVbad_array_new_length_std__);
}
// 1400019B0: using guessed type void __fastcall __noreturn sub_1400019B0();

//----- (00000001400019E0) ----------------------------------------------------
_QWORD *__fastcall sub_1400019E0(_QWORD *a1, __int64 a2)
{
  sub_140001A20(a1, a2);
  *a1 = &std::bad_array_new_length::`vftable';
  return a1;
}
// 140006408: using guessed type void *std::bad_array_new_length::`vftable';

//----- (0000000140001A20) ----------------------------------------------------
_QWORD *__fastcall sub_140001A20(_QWORD *a1, __int64 a2)
{
  sub_140001760(a1, a2);
  *a1 = &std::bad_alloc::`vftable';
  return a1;
}
// 1400063E0: using guessed type void *std::bad_alloc::`vftable';

//----- (0000000140001A70) ----------------------------------------------------
void *__fastcall sub_140001A70(size_t a1)
{
  return operator new(a1);
}

//----- (0000000140001A90) ----------------------------------------------------
_QWORD *__fastcall sub_140001A90(_QWORD *a1, _QWORD *a2)
{
  _QWORD *result; // rax
  __int64 v3; // [rsp+28h] [rbp-20h]

  *a2 += 39i64;
  v3 = *(_QWORD *)(*a1 - 8i64);
  if ( (unsigned __int64)(*a1 - v3) < 8 || (unsigned __int64)(*a1 - v3) > 0x27 )
    invalid_parameter_noinfo_noreturn();
  result = a1;
  *a1 = v3;
  return result;
}

//----- (0000000140001B30) ----------------------------------------------------
void sub_140001B30()
{
  ;
}

//----- (0000000140001B70) ----------------------------------------------------
void __noreturn sub_140001B70()
{
  std::_Xlength_error("string too long");
}
// 140001B70: using guessed type void __fastcall __noreturn sub_140001B70();
// 140006110: using guessed type void __fastcall __noreturn std::_Xlength_error(const char *);

//----- (0000000140001B90) ----------------------------------------------------
std::exception *__fastcall sub_140001B90(std::exception *a1)
{
  std::exception::exception(a1, "bad cast", 1);
  *(_QWORD *)a1 = &std::bad_cast::`vftable';
  return a1;
}
// 1400064C8: using guessed type void *std::bad_cast::`vftable';

//----- (0000000140001BD0) ----------------------------------------------------
void __noreturn sub_140001BD0()
{
  char pExceptionObject[40]; // [rsp+20h] [rbp-28h] BYREF

  sub_140001B90((std::exception *)pExceptionObject);
  CxxThrowException(pExceptionObject, (_ThrowInfo *)&_TI2_AVbad_cast_std__);
}
// 140001BD0: using guessed type void __fastcall __noreturn sub_140001BD0();

//----- (0000000140001C00) ----------------------------------------------------
_QWORD *__fastcall sub_140001C00(_QWORD *a1, __int64 a2)
{
  sub_140001760(a1, a2);
  *a1 = &std::bad_cast::`vftable';
  return a1;
}
// 1400064C8: using guessed type void *std::bad_cast::`vftable';

//----- (0000000140001C40) ----------------------------------------------------
__int64 (__fastcall ***__fastcall sub_140001C40(__int64 a1))(_QWORD, __int64)
{
  __int64 (__fastcall ***result)(_QWORD, __int64); // rax

  result = (__int64 (__fastcall ***)(_QWORD, __int64))a1;
  if ( *(_QWORD *)(a1 + 8) )
  {
    result = (__int64 (__fastcall ***)(_QWORD, __int64))(*(__int64 (__fastcall **)(_QWORD))(**(_QWORD **)(a1 + 8) + 16i64))(*(_QWORD *)(a1 + 8));
    if ( result )
      return (__int64 (__fastcall ***)(_QWORD, __int64))(**result)(result, 1i64);
  }
  return result;
}

//----- (0000000140001CB0) ----------------------------------------------------
__int64 __fastcall sub_140001CB0(__int64 a1, unsigned __int64 a2)
{
  __int64 v3; // [rsp+20h] [rbp-28h]
  __int64 v4; // [rsp+30h] [rbp-18h]

  if ( a2 >= *(_QWORD *)(*(_QWORD *)(a1 + 8) + 24i64) )
    v3 = 0i64;
  else
    v3 = *(_QWORD *)(*(_QWORD *)(*(_QWORD *)(a1 + 8) + 16i64) + 8 * a2);
  if ( v3 || !*(_BYTE *)(*(_QWORD *)(a1 + 8) + 36i64) )
    return v3;
  v4 = std::locale::_Getgloballocale();
  if ( a2 >= *(_QWORD *)(v4 + 24) )
    return 0i64;
  else
    return *(_QWORD *)(*(_QWORD *)(v4 + 16) + 8 * a2);
}
// 140006140: using guessed type __int64 std::locale::_Getgloballocale(void);

//----- (0000000140001D60) ----------------------------------------------------
__int64 __fastcall sub_140001D60(void *a1, unsigned __int64 a2)
{
  __int64 result; // rax

  result = 0i64;
  memset(a1, 0, a2);
  return result;
}

//----- (0000000140001D80) ----------------------------------------------------
__int64 sub_140001D80()
{
  return *(unsigned int *)sub_140002130(input_1, ++input_2);
}
// 140009710: using guessed type __int64 input_2;
// 140009730: using guessed type _QWORD input_1[3];

//----- (0000000140001DB0) ----------------------------------------------------
__int64 sub_140001DB0()
{
  __int64 v0; // r8
  __int64 result; // rax
  __int64 v2; // rcx
  __int64 v3; // rcx
  __int64 v4; // rcx
  __int64 v5; // rcx
  bool v6; // [rsp+24h] [rbp-84h]
  bool v7; // [rsp+28h] [rbp-80h]
  int v8; // [rsp+2Ch] [rbp-7Ch]
  int v9; // [rsp+30h] [rbp-78h]
  int v10; // [rsp+34h] [rbp-74h]
  int v11; // [rsp+38h] [rbp-70h]
  int v12; // [rsp+3Ch] [rbp-6Ch]
  _DWORD *v13; // [rsp+40h] [rbp-68h]
  unsigned __int64 v14; // [rsp+48h] [rbp-60h]
  __int64 v15; // [rsp+50h] [rbp-58h]
  _DWORD *v16; // [rsp+58h] [rbp-50h]
  __int64 v17; // [rsp+60h] [rbp-48h]
  __int64 v18; // [rsp+68h] [rbp-40h]
  __int64 v19; // [rsp+70h] [rbp-38h]
  __int64 v20; // [rsp+78h] [rbp-30h]
  _DWORD *v21; // [rsp+80h] [rbp-28h]
  __int64 v22; // [rsp+88h] [rbp-20h]
  __int64 v23; // [rsp+90h] [rbp-18h]

  v8 = *(_DWORD *)sub_140002130(input_1, input_2);// =8==input_1 + 4*input_2
                                                // 0 2
                                                // 4 1
                                                // 8 0

  result = v8 - 1;
  switch ( v8 )
  {
    case 1:
      v15 = (int)sub_140001D80(0x140000000ui64);
      v9 = sub_140001D80(v2);
      v16 = (_DWORD *)sub_140002130(&qword_140009748, v9);
      result = sub_140002130(&qword_140009718, v15);
      *(_DWORD *)result = *v16;
      break;
    case 2:
      v22 = (int)sub_140001D80(0x140000000ui64);
      v14 = (int)sub_140001D80(v5);
      if ( v14 >= unknown_libname_19(&password) )
        goto LABEL_14;
      v12 = *(char *)sub_1400022A0(&password, v14);
      result = sub_140002130(&qword_140009718, v22);
      *(_DWORD *)result = v12;
      break;
    case 3:
      v17 = (int)sub_140001D80(0x140000000ui64);
      v18 = (int)sub_140001D80(v3);
      v13 = (_DWORD *)sub_140002130(&qword_140009718, v17);
      result = (unsigned int)(*(_DWORD *)sub_140002130(&qword_140009718, v18) ^ *v13);
      *v13 = result;
      break;
    case 4:
      v19 = (int)sub_140001D80(0x140000000ui64);
      v20 = (int)sub_140001D80(v4);
      v21 = (_DWORD *)sub_140002130(&qword_140009718, v19);
      v6 = *v21 == *(_DWORD *)sub_140002130(&qword_140009718, v20);
      result = v6;
      byte_140009780 = v6;
      break;
    case 5:
      v10 = sub_140001D80(0x140000000ui64);
      result = (unsigned __int8)byte_140009780;
      if ( byte_140009780 )
      {
        result = v10 + input_2;
        input_2 = result;
      }
      break;
    case 6:
      v11 = sub_140001D80(0x140000000ui64);
      result = (unsigned __int8)byte_140009780;
      if ( !byte_140009780 )
      {
        result = v11 + input_2;
        input_2 = result;
      }
      break;
    case 7:
      result = sub_140002BE0(std::cout, "congrat!", v0);
      input_2 = 0x7FFFFFFFi64;
      break;
    case 8:
LABEL_14:
      result = sub_140002BE0(std::cout, "try again..", v0);
      input_2 = 0x7FFFFFFFi64;
      break;
    case 9:
      v23 = (int)sub_140001D80(0x140000000ui64);
      v7 = v23 == unknown_libname_19(&password);
      result = v7;
      byte_140009780 = v7;
      break;
    default:
      return result;
  }
  return result;
}
// 140001E11: variable 'v2' is possibly undefined
// 140001E5E: variable 'v3' is possibly undefined
// 140001EB6: variable 'v4' is possibly undefined
// 140001F8E: variable 'v0' is possibly undefined
// 140001FB2: variable 'v5' is possibly undefined
// 140001D80: using guessed type __int64 __fastcall sub_140001D80(_QWORD);
// 140002130: using guessed type __int64 __fastcall sub_140002130(_QWORD, _QWORD);
// 140002290: using guessed type __int64 __fastcall unknown_libname_19(_QWORD);
// 1400022A0: using guessed type __int64 __fastcall sub_1400022A0(_QWORD, _QWORD);
// 140002BE0: using guessed type __int64 __fastcall sub_140002BE0(_QWORD, _QWORD, _QWORD);
// 140009710: using guessed type __int64 qword_140009710;
// 140009730: using guessed type _QWORD qword_140009730[3];
// 140009780: using guessed type char byte_140009780;

//----- (00000001400020A0) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  sub_140002BE0(std::cout, "type password: ", envp);
  sub_140002FB0(std::cin, (__int64)&password);
  while ( input_2 < (unsigned __int64)sub_140002160(input_1) )
  {
    sub_140001DB0();
    ++input_2;
  }
  return 0;
}
// 140002BE0: using guessed type __int64 __fastcall sub_140002BE0(_QWORD, _QWORD, _QWORD);
// 140009710: using guessed type __int64 qword_140009710;
// 140009730: using guessed type _QWORD qword_140009730[3];

//----- (0000000140002130) ----------------------------------------------------
__int64 __fastcall sub_140002130(_QWORD *a1, __int64 a2)
{
  return *a1 + 4 * a2;
}

//----- (0000000140002160) ----------------------------------------------------
__int64 __fastcall sub_140002160(_QWORD *a1)
{
  return (__int64)(a1[1] - *a1) >> 2;
}

//----- (0000000140002190) ----------------------------------------------------
__int64 *__fastcall sub_140002190(__int64 *a1)
{
  return sub_1400023D0(a1);
}

//----- (00000001400021B0) ----------------------------------------------------
__int64 __fastcall sub_1400021B0(__int64 a1, __FrameHandler3::TryBlockMap *a2, __int64 a3)
{
  __int64 v3; // rax
  unsigned __int64 v4; // rax
  unsigned __int8 v6; // [rsp+20h] [rbp-28h]
  struct _xDISPATCHER_CONTEXT *v7; // [rsp+28h] [rbp-20h] BYREF
  __int64 v8[3]; // [rsp+30h] [rbp-18h] BYREF

  sub_140003310(a1, v6, a3);
  v7 = __FrameHandler3::TryBlockMap::getpDC(a2);
  v8[0] = unknown_libname_20(a2);
  v3 = sub_140002390(a2);
  v4 = unknown_libname_18(v3);
  sub_140003350(a1, v4, (__int64)v8, (__int64)&v7);
  return a1;
}
// 1400021CD: variable 'v6' is possibly undefined
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 1400023C0: using guessed type __int64 __fastcall unknown_libname_20(_QWORD);
// 1400021B0: using guessed type __int64 var_18[3];

//----- (0000000140002230) ----------------------------------------------------
__int64 __fastcall sub_140002230(__int64 a1, unsigned __int64 a2, const void *a3, __int64 a4)
{
  unsigned __int8 v5; // [rsp+20h] [rbp-18h]

  sub_140003310(a1, v5, a4);
  sub_140003450(a1, a2, a3);
  return a1;
}
// 140002252: variable 'v5' is possibly undefined

//----- (00000001400022A0) ----------------------------------------------------
__int64 __fastcall sub_1400022A0(__int64 a1, __int64 a2)
{
  return a2 + unknown_libname_7(a1);
}
// 140002720: using guessed type __int64 __fastcall unknown_libname_7(_QWORD);

//----- (0000000140002300) ----------------------------------------------------
void *__fastcall sub_140002300(void *a1)
{
  sub_140003570((__int64)a1);
  __crt_win32_buffer_no_resizing::deallocate(a1, (const struct __crt_win32_buffer_empty_debug_info *)&unk_140006471);
  sub_140002580((__int64)a1);
  return a1;
}

//----- (0000000140002350) ----------------------------------------------------
void sub_140002350()
{
  sub_140002370();
}

//----- (0000000140002370) ----------------------------------------------------
void sub_140002370()
{
  sub_140001B30();
}

//----- (0000000140002390) ----------------------------------------------------
__int64 __fastcall sub_140002390(_QWORD *a1)
{
  return (__int64)(a1[1] - *a1) >> 2;
}

//----- (00000001400023D0) ----------------------------------------------------
__int64 *__fastcall sub_1400023D0(__int64 *a1)
{
  __int64 *result; // rax
  __int64 v2; // [rsp+30h] [rbp-28h]
  _QWORD *v3; // [rsp+38h] [rbp-20h]
  _QWORD *v4; // [rsp+40h] [rbp-18h]

  v2 = sub_1400024A0((__int64)a1);
  v3 = a1 + 1;
  v4 = a1 + 2;
  sub_140001B30();
  result = a1;
  if ( *a1 )
  {
    _castguard_slow_path_check_nop(*a1, *v3, v2);
    sub_140002830(v2, *a1, (*v4 - *a1) >> 2);
    *a1 = 0i64;
    *v3 = 0i64;
    result = a1 + 2;
    *v4 = 0i64;
  }
  return result;
}
// 1400035A0: using guessed type __int64 __fastcall _castguard_slow_path_check_nop(_QWORD, _QWORD, _QWORD);

//----- (00000001400024A0) ----------------------------------------------------
__int64 __fastcall sub_1400024A0(__int64 a1)
{
  return unknown_libname_18(a1);
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);

//----- (0000000140002580) ----------------------------------------------------
__int64 __fastcall sub_140002580(__int64 a1)
{
  char v2[8]; // [rsp+20h] [rbp-18h] BYREF
  __int64 v3; // [rsp+28h] [rbp-10h]

  v3 = a1;
  *(_QWORD *)(a1 + 16) = 0i64;
  *(_QWORD *)(v3 + 24) = 15i64;
  v2[0] = 0;
  return unknown_libname_11(v3, v2);
}
// 140002A20: using guessed type __int64 __fastcall unknown_libname_11(_QWORD, _QWORD);
// 140002580: using guessed type char var_18[8];

//----- (00000001400025E0) ----------------------------------------------------
_QWORD *__fastcall sub_1400025E0(_QWORD *a1, char a2)
{
  char v3; // [rsp+20h] [rbp-28h] BYREF
  char v4[7]; // [rsp+21h] [rbp-27h] BYREF
  unsigned __int64 v5; // [rsp+28h] [rbp-20h]
  __int64 v6; // [rsp+30h] [rbp-18h]
  char v7; // [rsp+58h] [rbp+10h] BYREF

  v7 = a2;
  v5 = a1[2];
  if ( v5 >= a1[3] )
  {
    memset(v4, 0, 1ui64);
    return sub_1400035B0(a1, 1ui64, v4[0], v7);
  }
  else
  {
    a1[2] = v5 + 1;
    v6 = unknown_libname_7(a1);
    unknown_libname_11(v5 + v6, &v7);
    v3 = 0;
    return (_QWORD *)unknown_libname_11(v6 + v5 + 1, &v3);
  }
}
// 140002720: using guessed type __int64 __fastcall unknown_libname_7(_QWORD);
// 140002A20: using guessed type __int64 __fastcall unknown_libname_11(_QWORD, _QWORD);

//----- (00000001400026B0) ----------------------------------------------------
__int64 sub_1400026B0(__int64 a1, char *a2, const void *a3, unsigned __int64 a4, ...)
{
  char v5[24]; // [rsp+20h] [rbp-18h] BYREF
  va_list va; // [rsp+60h] [rbp+28h] BYREF

  va_start(va, a4);
  sub_140002800(a2, a3, a4);
  unknown_libname_11(&a2[a4], va);
  v5[0] = 0;
  return unknown_libname_11(&a2[a4 + 1], v5);
}
// 140002A20: using guessed type __int64 __fastcall unknown_libname_11(_QWORD, _QWORD);
// 1400026B0: using guessed type char var_18[24];

//----- (0000000140002760) ----------------------------------------------------
__int64 sub_140002760()
{
  return 0xFFFFFFFFi64;
}

//----- (0000000140002800) ----------------------------------------------------
void *__fastcall sub_140002800(void *a1, const void *a2, unsigned __int64 a3)
{
  qmemcpy(a1, a2, a3);
  return a1;
}

//----- (0000000140002830) ----------------------------------------------------
__int64 __fastcall sub_140002830(__int64 a1, __int64 a2, __int64 a3)
{
  return std::_Deallocate<16,0>(a2, 4 * a3);
}
// 1400037E0: using guessed type __int64 __fastcall std::_Deallocate<16,0>(_QWORD, _QWORD);

//----- (00000001400028B0) ----------------------------------------------------
__int64 __fastcall sub_1400028B0(__int64 a1, __int64 a2)
{
  __int64 v2; // rax
  char v4[24]; // [rsp+20h] [rbp-18h] BYREF

  v4[0] = 0;
  *(_QWORD *)(a1 + 16) = a2;
  v2 = unknown_libname_7(a1);
  return unknown_libname_11(a2 + v2, v4);
}
// 140002720: using guessed type __int64 __fastcall unknown_libname_7(_QWORD);
// 140002A20: using guessed type __int64 __fastcall unknown_libname_11(_QWORD, _QWORD);
// 1400028B0: using guessed type char var_18[24];

//----- (0000000140002A40) ----------------------------------------------------
void __fastcall sub_140002A40(__int64 a1, unsigned __int64 a2)
{
  if ( *(_QWORD *)(a1 + 16) < a2 )
    sub_140002A80();
}

//----- (0000000140002A80) ----------------------------------------------------
void sub_140002A80()
{
  std::_Xout_of_range("invalid string position");
}
// 140006120: using guessed type void __fastcall std::_Xout_of_range(const char *);

//----- (0000000140002AA0) ----------------------------------------------------
__int64 __fastcall sub_140002AA0(__int64 a1)
{
  struct std::_Facet_base *v2; // [rsp+20h] [rbp-48h]
  __int64 v3; // [rsp+28h] [rbp-40h]
  unsigned __int64 v4; // [rsp+30h] [rbp-38h]
  struct std::_Facet_base *v5; // [rsp+40h] [rbp-28h] BYREF
  char v6[8]; // [rsp+48h] [rbp-20h] BYREF
  __int64 (__fastcall ***v7)(_QWORD, __int64); // [rsp+50h] [rbp-18h] BYREF

  std::_Lockit::_Lockit((std::_Lockit *)v6, 0);
  v5 = (struct std::_Facet_base *)qword_140009788;
  v4 = std::locale::id::operator unsigned __int64(std::ctype<char>::id);
  v3 = sub_140001CB0(a1, v4);
  if ( !v3 )
  {
    if ( v5 )
    {
      v3 = (__int64)v5;
    }
    else
    {
      if ( std::ctype<char>::_Getcat(&v5, a1) == -1 )
        sub_140001BD0();
      v2 = v5;
      sub_140001D60(&v7, 8ui64);
      std::_Unique_ptr_base<std::_Facet_base,std::default_delete<std::_Facet_base>>::_Unique_ptr_base<std::_Facet_base,std::default_delete<std::_Facet_base>>(
        &v7,
        v2);
      std::_Facet_Register(v2);
      (*(void (__fastcall **)(struct std::_Facet_base *))(*(_QWORD *)v2 + 8i64))(v2);
      qword_140009788 = (__int64)v5;
      v3 = (__int64)v5;
      sub_140003AD0((__int64)&v7);
      sub_140003B00(&v7);
    }
  }
  std::_Lockit::~_Lockit((std::_Lockit *)v6);
  return v3;
}
// 140001BD0: using guessed type void __noreturn sub_140001BD0(void);
// 140003F50: using guessed type __int64 __fastcall std::_Unique_ptr_base<std::_Facet_base,std::default_delete<std::_Facet_base>>::_Unique_ptr_base<std::_Facet_base,std::default_delete<std::_Facet_base>>(_QWORD, _QWORD);
// 1400060C0: using guessed type __int64 __fastcall std::ctype<char>::_Getcat(_QWORD, _QWORD);
// 1400060D0: using guessed type __int64 __fastcall std::locale::id::operator unsigned __int64(_QWORD);
// 1400060E0: using guessed type void std::_Lockit::~_Lockit(std::_Lockit *__hidden this);
// 140006150: using guessed type _QWORD __fastcall std::_Lockit::_Lockit(std::_Lockit *__hidden this, _DWORD);
// 140009788: using guessed type __int64 qword_140009788;
// 140002AA0: using guessed type char var_20[8];

//----- (0000000140002BE0) ----------------------------------------------------
__int64 __fastcall sub_140002BE0(__int64 a1, __int64 a2)
{
  unsigned int v3; // [rsp+20h] [rbp-88h]
  unsigned __int8 v4; // [rsp+24h] [rbp-84h]
  unsigned __int8 v5; // [rsp+25h] [rbp-83h]
  __int64 v6; // [rsp+28h] [rbp-80h]
  __int64 v7; // [rsp+30h] [rbp-78h]
  int v8; // [rsp+40h] [rbp-68h] BYREF
  int v9; // [rsp+44h] [rbp-64h] BYREF
  int v10; // [rsp+48h] [rbp-60h]
  int v11; // [rsp+4Ch] [rbp-5Ch] BYREF
  int v12; // [rsp+50h] [rbp-58h] BYREF
  __int64 v13; // [rsp+58h] [rbp-50h]
  __int64 v14; // [rsp+60h] [rbp-48h]
  __int64 v15; // [rsp+68h] [rbp-40h]
  __int64 v16; // [rsp+70h] [rbp-38h]
  __int64 v17; // [rsp+78h] [rbp-30h]
  __int64 v18; // [rsp+80h] [rbp-28h]
  char v19[16]; // [rsp+88h] [rbp-20h] BYREF

  v3 = 0;
  v7 = unknown_libname_9(a2);
  if ( std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1)) <= 0
    || std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1)) <= v7 )
  {
    v13 = 0i64;
  }
  else
  {
    v13 = std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1)) - v7;
  }
  v6 = v13;
  sub_1400039F0(v19, a1);
  if ( (unsigned __int8)std::optional<unsigned __int64>::operator bool(v19) )
  {
    if ( (std::ios_base::flags((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1)) & 0x1C0) != 64 )
    {
      while ( v6 > 0 )
      {
        v4 = std::ios::fill(*(int *)(*(_QWORD *)a1 + 4i64) + a1);
        v14 = std::ios::rdbuf(*(int *)(*(_QWORD *)a1 + 4i64) + a1);
        v8 = std::streambuf::sputc(v14, v4);
        v9 = sub_140002760();
        if ( (unsigned __int8)unknown_libname_8(&v9, &v8) )
        {
          v3 = 4;
          break;
        }
        --v6;
      }
    }
    if ( !v3 )
    {
      v15 = std::ios::rdbuf(*(int *)(*(_QWORD *)a1 + 4i64) + a1);
      v16 = std::streambuf::sputn(v15, a2, v7);
      if ( v16 != v7 )
        v3 = 4;
    }
    if ( !v3 )
    {
      while ( v6 > 0 )
      {
        v5 = std::ios::fill(*(int *)(*(_QWORD *)a1 + 4i64) + a1);
        v17 = std::ios::rdbuf(*(int *)(*(_QWORD *)a1 + 4i64) + a1);
        v10 = std::streambuf::sputc(v17, v5);
        v11 = v10;
        v12 = sub_140002760();
        if ( (unsigned __int8)unknown_libname_8(&v12, &v11) )
        {
          v3 |= 4u;
          break;
        }
        --v6;
      }
    }
    std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1), 0i64);
  }
  else
  {
    v3 = 4;
  }
  std::ios::setstate(*(int *)(*(_QWORD *)a1 + 4i64) + a1, v3, 0i64);
  v18 = a1;
  sub_140003990(v19);
  return v18;
}
// 140002BE0: could not find valid save-restore pair for rbp
// 140002760: using guessed type __int64 sub_140002760(void);
// 140002770: using guessed type __int64 __fastcall unknown_libname_8(_QWORD, _QWORD);
// 1400027C0: using guessed type __int64 __fastcall unknown_libname_9(_QWORD);
// 1400038D0: using guessed type __int64 __fastcall std::optional<unsigned __int64>::operator bool(_QWORD);
// 140003990: using guessed type __int64 __fastcall sub_140003990(_QWORD);
// 1400039F0: using guessed type __int64 __fastcall sub_1400039F0(_QWORD, _QWORD);
// 140006080: using guessed type __int64 __fastcall std::ios::fill(_QWORD);
// 140006090: using guessed type __int64 __fastcall std::streambuf::sputc(_QWORD, _QWORD);
// 1400060A0: using guessed type __int64 __fastcall std::ios_base::width(std::ios_base *__hidden this, __int64);
// 1400060A8: using guessed type __int64 __fastcall std::ios::setstate(_QWORD, _QWORD, _QWORD);
// 1400060B0: using guessed type _DWORD std::ios_base::flags(std::ios_base *__hidden this);
// 1400060D8: using guessed type __int64 __fastcall std::streambuf::sputn(_QWORD, _QWORD, _QWORD);
// 140006138: using guessed type __int64 __fastcall std::ios::rdbuf(_QWORD);
// 140006158: using guessed type __int64 std::ios_base::width(std::ios_base *__hidden this);

//----- (0000000140002FB0) ----------------------------------------------------
__int64 __fastcall sub_140002FB0(__int64 a1, _QWORD *a2)
{
  unsigned __int8 v2; // al
  __int64 v3; // rdx
  char v4; // al
  char v6; // [rsp+20h] [rbp-A8h]
  unsigned int v7; // [rsp+24h] [rbp-A4h]
  __int64 v8; // [rsp+28h] [rbp-A0h]
  int v9; // [rsp+38h] [rbp-90h] BYREF
  __int64 v10; // [rsp+40h] [rbp-88h]
  __int64 v11; // [rsp+48h] [rbp-80h]
  __int64 v12; // [rsp+50h] [rbp-78h]
  unsigned __int64 v13; // [rsp+58h] [rbp-70h]
  __int64 v14; // [rsp+60h] [rbp-68h]
  __int64 v15; // [rsp+68h] [rbp-60h]
  __int64 v16; // [rsp+70h] [rbp-58h]
  __int64 v17; // [rsp+78h] [rbp-50h]
  __int64 v18; // [rsp+80h] [rbp-48h]
  char v19[16]; // [rsp+88h] [rbp-40h] BYREF
  int v20; // [rsp+98h] [rbp-30h] BYREF
  char v21[16]; // [rsp+A0h] [rbp-28h] BYREF

  v7 = 0;
  v6 = 0;
  sub_1400038E0((__int64)v21, a1, 0);
  if ( (unsigned __int8)std::optional<unsigned __int64>::operator bool(v21) )
  {
    v10 = std::ios_base::getloc(*(int *)(*(_QWORD *)a1 + 4i64) + a1, v19);
    v11 = v10;
    v17 = sub_140002AA0(v10);
    sub_140001C40((__int64)v19);
    sub_140003C00((__int64)a2, 0i64);
    v12 = std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1));
    if ( v12 <= 0
      || (v13 = std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1)),
          v13 >= std::string::shrink_to_fit(a2)) )
    {
      v8 = std::string::shrink_to_fit(a2);
    }
    else
    {
      v14 = std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1));
      v8 = v14;
    }
    v15 = std::ios::rdbuf(*(int *)(*(_QWORD *)a1 + 4i64) + a1);
    v20 = std::streambuf::sgetc(v15);
    while ( v8 )
    {
      v9 = sub_140002760();
      if ( (unsigned __int8)unknown_libname_8(&v9, &v20) )
      {
        v7 = 1;
        break;
      }
      v2 = std::_Atomic_reinterpret_as<char,char>(&v20);
      LOWORD(v3) = 72;
      if ( (unsigned __int8)std::ctype<char>::is(v17, v3, v2) )
        break;
      v4 = std::_Atomic_reinterpret_as<char,char>(&v20);
      sub_1400025E0(a2, v4);
      v6 = 1;
      --v8;
      v16 = std::ios::rdbuf(*(int *)(*(_QWORD *)a1 + 4i64) + a1);
      v20 = std::streambuf::snextc(v16);
    }
  }
  std::ios_base::width((std::ios_base *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1), 0i64);
  if ( !v6 )
    v7 |= 2u;
  std::ios::setstate(*(int *)(*(_QWORD *)a1 + 4i64) + a1, v7, 0i64);
  v18 = a1;
  sub_140003880((__int64)v21);
  return v18;
}
// 140002FB0: could not find valid save-restore pair for rbp
// 140003225: variable 'v3' is possibly undefined
// 140002770: using guessed type __int64 __fastcall unknown_libname_8(_QWORD, _QWORD);
// 1400027B0: using guessed type __int64 __fastcall std::_Atomic_reinterpret_as<char,char>(_QWORD);
// 140002900: using guessed type __int64 __fastcall std::string::shrink_to_fit(_QWORD);
// 1400038D0: using guessed type __int64 __fastcall std::optional<unsigned __int64>::operator bool(_QWORD);
// 140006088: using guessed type __int64 __fastcall std::streambuf::sgetc(_QWORD);
// 140006098: using guessed type __int64 __fastcall std::ios_base::getloc(_QWORD, _QWORD);
// 1400060A0: using guessed type __int64 __fastcall std::ios_base::width(std::ios_base *__hidden this, __int64);
// 1400060A8: using guessed type __int64 __fastcall std::ios::setstate(_QWORD, _QWORD, _QWORD);
// 1400060C8: using guessed type __int64 __fastcall std::ctype<char>::is(_QWORD, _QWORD, _QWORD);
// 1400060E8: using guessed type __int64 __fastcall std::streambuf::snextc(_QWORD);
// 140006138: using guessed type __int64 __fastcall std::ios::rdbuf(_QWORD);
// 140006158: using guessed type __int64 std::ios_base::width(std::ios_base *__hidden this);

//----- (0000000140003310) ----------------------------------------------------
__int64 __fastcall sub_140003310(__int64 a1, __int64 a2, __int64 a3)
{
  unknown_libname_18(a3);
  unknown_libname_21(a1);
  return a1;
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 140003B40: using guessed type __int64 __fastcall unknown_libname_21(_QWORD);

//----- (0000000140003350) ----------------------------------------------------
void __fastcall sub_140003350(__int64 a1, unsigned __int64 a2, __int64 a3, __int64 a4)
{
  __int64 *v4; // rax
  __int64 v5; // [rsp+30h] [rbp-38h]
  __int64 *v6; // [rsp+38h] [rbp-30h]
  __int64 *v7; // [rsp+40h] [rbp-28h] BYREF
  char v8[8]; // [rsp+48h] [rbp-20h] BYREF

  v5 = sub_1400024A0(a1);
  std::_Fake_proxy_ptr_impl::_Fake_proxy_ptr_impl(
    (std::_Fake_proxy_ptr_impl *)v8,
    (const struct std::_Fake_allocator *)&unk_140006471,
    (const struct std::_Container_base0 *)a1);
  if ( a2 )
  {
    sub_140003B80((__int64 *)a1, a2);
    v7 = (__int64 *)a1;
    v6 = (__int64 *)unknown_libname_18(a4);
    v4 = (__int64 *)unknown_libname_18(a3);
    *(_QWORD *)(a1 + 8) = sub_140003F80(*v4, *v6, *(_QWORD *)a1, v5);
    v7 = 0i64;
    sub_1400038A0(&v7);
  }
  sub_140001B30();
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 140003350: using guessed type char var_20[8];

//----- (0000000140003450) ----------------------------------------------------
void __fastcall sub_140003450(__int64 a1, unsigned __int64 a2, const void *a3)
{
  __int64 v3; // [rsp+30h] [rbp-28h]
  __int64 *v4; // [rsp+38h] [rbp-20h] BYREF
  char v5[8]; // [rsp+40h] [rbp-18h] BYREF

  v3 = sub_1400024A0(a1);
  std::_Fake_proxy_ptr_impl::_Fake_proxy_ptr_impl(
    (std::_Fake_proxy_ptr_impl *)v5,
    (const struct std::_Fake_allocator *)&unk_140006471,
    (const struct std::_Container_base0 *)a1);
  if ( a2 )
  {
    sub_140003B80((__int64 *)a1, a2);
    v4 = (__int64 *)a1;
    *(_QWORD *)(a1 + 8) = sub_1400040A0(*(_QWORD *)a1, a2, a3, v3);
    v4 = 0i64;
    sub_1400038A0(&v4);
  }
  sub_140001B30();
}
// 140003450: using guessed type char var_18[8];

//----- (0000000140003570) ----------------------------------------------------
__int64 __fastcall sub_140003570(__int64 a1)
{
  unknown_libname_18(a1);
  sub_140003C40(a1);
  return a1;
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);

//----- (00000001400035B0) ----------------------------------------------------
_QWORD *__fastcall sub_1400035B0(_QWORD *a1, unsigned __int64 a2, char a3, char a4)
{
  __int64 v4; // rax
  const void *v5; // rax
  unsigned __int64 v8; // [rsp+38h] [rbp-50h]
  unsigned __int64 v9; // [rsp+48h] [rbp-40h]
  unsigned __int64 v10; // [rsp+50h] [rbp-38h]
  __int64 v11; // [rsp+58h] [rbp-30h]
  __int64 v12; // [rsp+60h] [rbp-28h]
  char *v13; // [rsp+68h] [rbp-20h]
  __int64 v14; // [rsp+70h] [rbp-18h] BYREF
  char v17; // [rsp+A0h] [rbp+18h] BYREF
  char v18; // [rsp+A8h] [rbp+20h]

  v18 = a4;
  v17 = a3;
  v8 = a1[2];
  if ( std::string::shrink_to_fit(a1) - v8 < a2 )
    sub_140001B70();
  v10 = a1[3];
  v9 = sub_140003BC0((__int64)a1, a2 + v8);
  v12 = sub_1400024A0((__int64)a1);
  v4 = v9 + 1;
  if ( v9 == -1i64 )
    v4 = -1i64;
  v14 = std::allocator<char>::allocate(v12, v4);
  sub_140001B30();
  a1[2] = a2 + v8;
  a1[3] = v9;
  v13 = (char *)unknown_libname_18(v14);
  if ( v10 < 0x10 )
  {
    sub_1400026B0((__int64)&v17, v13, a1, v8, v18);
    sub_140003790((__int64)a1, (__int64)&v14);
  }
  else
  {
    v11 = *a1;
    v5 = (const void *)unknown_libname_18(*a1);
    sub_1400026B0((__int64)&v17, v13, v5, v8, v18);
    std::allocator<char>::deallocate(v12, v11, v10 + 1);
    *a1 = v14;
  }
  return a1;
}
// 140001B70: using guessed type void __noreturn sub_140001B70(void);
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 140002900: using guessed type __int64 __fastcall std::string::shrink_to_fit(_QWORD);
// 1400029C0: using guessed type __int64 __fastcall std::allocator<char>::allocate(_QWORD, _QWORD);
// 1400029F0: using guessed type __int64 __fastcall std::allocator<char>::deallocate(_QWORD, _QWORD, _QWORD);

//----- (0000000140003790) ----------------------------------------------------
__int64 __fastcall sub_140003790(__int64 a1, __int64 a2)
{
  __int64 v2; // rax
  __int64 v3; // rax
  __int64 result; // rax
  _QWORD *v5; // [rsp+20h] [rbp-18h]

  v2 = unknown_libname_18(a1);
  v3 = unknown_libname_18(v2);
  v5 = (_QWORD *)unknown_libname_17(8i64, v3);
  result = *(_QWORD *)unknown_libname_18(a2);
  *v5 = result;
  return result;
}
// 140001700: using guessed type __int64 __fastcall unknown_libname_17(_QWORD, _QWORD);
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);

//----- (0000000140003880) ----------------------------------------------------
__int64 __fastcall sub_140003880(__int64 a1)
{
  return sub_140003930(a1);
}

//----- (00000001400038A0) ----------------------------------------------------
__int64 *__fastcall sub_1400038A0(__int64 **a1)
{
  __int64 *result; // rax

  result = (__int64 *)a1;
  if ( *a1 )
    return sub_1400023D0(*a1);
  return result;
}

//----- (00000001400038E0) ----------------------------------------------------
__int64 __fastcall sub_1400038E0(__int64 a1, __int64 a2, unsigned __int8 a3)
{
  sub_140003C80(a1, a2);
  *(_BYTE *)(a1 + 8) = std::istream::_Ipfx(*(_QWORD *)a1, a3);
  return a1;
}
// 1400060F0: using guessed type __int64 __fastcall std::istream::_Ipfx(_QWORD, _QWORD);

//----- (0000000140003930) ----------------------------------------------------
__int64 __fastcall sub_140003930(__int64 a1)
{
  __int64 result; // rax

  result = std::ios::rdbuf(*(int *)(**(_QWORD **)a1 + 4i64) + *(_QWORD *)a1);
  if ( result )
    return (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)result + 16i64))(result);
  return result;
}
// 140006138: using guessed type __int64 __fastcall std::ios::rdbuf(_QWORD);

//----- (0000000140003990) ----------------------------------------------------
__int64 __fastcall sub_140003990(_QWORD *a1)
{
  if ( !std::uncaught_exception() )
    std::ostream::_Osfx(*a1);
  return sub_140003930(a1);
}
// 140003930: using guessed type __int64 __fastcall sub_140003930(_QWORD);
// 140006100: using guessed type __int64 __fastcall std::ostream::_Osfx(_QWORD);
// 140006130: using guessed type bool std::uncaught_exception(void);

//----- (00000001400039F0) ----------------------------------------------------
__int64 __fastcall sub_1400039F0(__int64 a1, __int64 a2)
{
  __int64 v3; // [rsp+20h] [rbp-18h]

  sub_140003C80(a1, a2);
  if ( std::ios_base::good((std::ios_base *)(*(int *)(*(_QWORD *)a2 + 4i64) + a2)) )
  {
    v3 = std::ios::tie(*(int *)(*(_QWORD *)a2 + 4i64) + a2);
    if ( v3 && v3 != a2 )
    {
      std::ostream::flush(v3);
      *(_BYTE *)(a1 + 8) = std::ios_base::good((std::ios_base *)(*(int *)(*(_QWORD *)a2 + 4i64) + a2));
    }
    else
    {
      *(_BYTE *)(a1 + 8) = 1;
    }
  }
  else
  {
    *(_BYTE *)(a1 + 8) = 0;
  }
  return a1;
}
// 1400060B8: using guessed type bool std::ios_base::good(std::ios_base *__hidden this);
// 1400060F8: using guessed type __int64 __fastcall std::ostream::flush(_QWORD);
// 140006108: using guessed type __int64 __fastcall std::ios::tie(_QWORD);

//----- (0000000140003AD0) ----------------------------------------------------
__int64 __fastcall sub_140003AD0(__int64 a1)
{
  __int64 v2[3]; // [rsp+20h] [rbp-18h] BYREF

  v2[0] = 0i64;
  return unknown_libname_15(a1, v2);
}
// 140004210: using guessed type __int64 __fastcall unknown_libname_15(_QWORD, _QWORD);
// 140003AD0: using guessed type __int64 var_18[3];

//----- (0000000140003B00) ----------------------------------------------------
__int64 __fastcall sub_140003B00(__int64 (__fastcall ****a1)(_QWORD, __int64))
{
  __int64 result; // rax
  __int64 v2; // rax

  result = (__int64)a1;
  if ( *a1 )
  {
    v2 = unknown_libname_18(a1);
    return sub_140003CF0(v2, *a1);
  }
  return result;
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);

//----- (0000000140003B80) ----------------------------------------------------
unsigned __int64 __fastcall sub_140003B80(__int64 *a1, unsigned __int64 a2)
{
  if ( a2 > std::_Tree<std::_Tmap_traits<void *,`anonymous namespace'::_Mutex_count_pair,std::less<void *>,std::_Crt_allocator<std::pair<void * const,`anonymous namespace'::_Mutex_count_pair>>,0>>::max_size(a1) )
    sub_140003D40();
  return sub_140003D60(a1, a2);
}
// 140003D40: using guessed type void __noreturn sub_140003D40(void);
// 140003DF0: using guessed type __int64 __fastcall std::_Tree<std::_Tmap_traits<void *,`anonymous namespace'::_Mutex_count_pair,std::less<void *>,std::_Crt_allocator<std::pair<void * const,`anonymous namespace'::_Mutex_count_pair>>,0>>::max_size(_QWORD);

//----- (0000000140003BC0) ----------------------------------------------------
unsigned __int64 __fastcall sub_140003BC0(__int64 a1, __int64 a2)
{
  unsigned __int64 v2; // rax

  v2 = std::string::shrink_to_fit(a1);
  return sub_140003E40(a2, *(_QWORD *)(a1 + 24), v2);
}
// 140002900: using guessed type __int64 __fastcall std::string::shrink_to_fit(_QWORD);

//----- (0000000140003C00) ----------------------------------------------------
__int64 __fastcall sub_140003C00(__int64 a1, unsigned __int64 a2)
{
  sub_140002A40(a1, a2);
  sub_1400028B0(a1, a2);
  return a1;
}

//----- (0000000140003C40) ----------------------------------------------------
__int64 __fastcall sub_140003C40(__int64 a1)
{
  unknown_libname_22(a1);
  *(_QWORD *)(a1 + 16) = 0i64;
  *(_QWORD *)(a1 + 24) = 0i64;
  return a1;
}
// 140003EF0: using guessed type __int64 __fastcall unknown_libname_22(_QWORD);

//----- (0000000140003C80) ----------------------------------------------------
__int64 __fastcall sub_140003C80(__int64 a1, __int64 a2)
{
  __int64 v3; // [rsp+20h] [rbp-18h]

  *(_QWORD *)a1 = a2;
  v3 = std::ios::rdbuf(*(int *)(**(_QWORD **)a1 + 4i64) + *(_QWORD *)a1);
  if ( v3 )
    (*(void (__fastcall **)(__int64))(*(_QWORD *)v3 + 8i64))(v3);
  return a1;
}
// 140006138: using guessed type __int64 __fastcall std::ios::rdbuf(_QWORD);

//----- (0000000140003CF0) ----------------------------------------------------
__int64 __fastcall sub_140003CF0(__int64 a1, __int64 (__fastcall ***a2)(_QWORD, __int64))
{
  __int64 result; // rax

  result = (__int64)a2;
  if ( a2 )
    return (**a2)(a2, 1i64);
  return result;
}

//----- (0000000140003D40) ----------------------------------------------------
void __noreturn sub_140003D40()
{
  std::_Xlength_error("vector too long");
}
// 140003D40: using guessed type void __fastcall __noreturn sub_140003D40();
// 140006110: using guessed type void __fastcall __noreturn std::_Xlength_error(const char *);

//----- (0000000140003D60) ----------------------------------------------------
unsigned __int64 __fastcall sub_140003D60(__int64 *a1, unsigned __int64 a2)
{
  __int64 v2; // rax
  __int64 v3; // rax
  unsigned __int64 result; // rax
  __int64 *v6; // [rsp+38h] [rbp-20h]
  unsigned __int64 *v7; // [rsp+40h] [rbp-18h]

  v6 = a1 + 1;
  v7 = (unsigned __int64 *)(a1 + 2);
  v2 = sub_1400024A0((__int64)a1);
  v3 = sub_140003F20(v2, a2);
  *a1 = v3;
  *v6 = v3;
  result = v3 + 4 * a2;
  *v7 = result;
  return result;
}

//----- (0000000140003E40) ----------------------------------------------------
unsigned __int64 __fastcall sub_140003E40(__int64 a1, unsigned __int64 a2, unsigned __int64 a3)
{
  unsigned __int64 v4; // [rsp+20h] [rbp-28h] BYREF
  __int64 v5; // [rsp+28h] [rbp-20h] BYREF

  v5 = a1 | 0xF;
  if ( (a1 | 0xFui64) > a3 )
    return a3;
  if ( a2 > a3 - a2 / 2 )
    return a3;
  v4 = a2 / 2 + a2;
  return *(_QWORD *)unknown_libname_10(&v5, &v4);
}
// 140002860: using guessed type __int64 __fastcall unknown_libname_10(_QWORD, _QWORD);

//----- (0000000140003F10) ----------------------------------------------------
__int64 sub_140003F10()
{
  return 0x3FFFFFFFFFFFFFFFi64;
}
// 140003F10: using guessed type __int64 __fastcall sub_140003F10();

//----- (0000000140003F20) ----------------------------------------------------
__int64 __fastcall sub_140003F20(__int64 a1, unsigned __int64 a2)
{
  __int64 v2; // rax

  v2 = sub_140004250(a2, a2);
  return std::_Allocate<16,std::_Default_allocate_traits,0>(v2);
}
// 140003840: using guessed type __int64 __fastcall std::_Allocate<16,std::_Default_allocate_traits,0>(_QWORD);

//----- (0000000140003F80) ----------------------------------------------------
__int64 __fastcall sub_140003F80(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // rax
  __int64 v6; // [rsp+20h] [rbp-48h]
  __int64 v7; // [rsp+28h] [rbp-40h]
  __int64 v8; // [rsp+70h] [rbp+8h] BYREF
  __int64 v9; // [rsp+78h] [rbp+10h] BYREF
  __int64 v10; // [rsp+80h] [rbp+18h]
  __int64 v11; // [rsp+88h] [rbp+20h]

  v11 = a4;
  v10 = a3;
  v9 = a2;
  v8 = a1;
  v6 = unknown_libname_20(&v8);
  v7 = unknown_libname_20(&v9);
  v4 = unknown_libname_18(v10);
  sub_140004370(v6, v7, v4);
  v10 += 4 * ((v7 - v6) >> 2);
  return v10;
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 1400023C0: using guessed type __int64 __fastcall unknown_libname_20(_QWORD);

//----- (00000001400040A0) ----------------------------------------------------
__int64 __fastcall sub_1400040A0(__int64 a1, __int64 a2, const void *a3, __int64 a4)
{
  __int64 v4; // rax
  __int64 v6; // [rsp+20h] [rbp-38h]
  _QWORD v7[3]; // [rsp+28h] [rbp-30h] BYREF

  if ( sub_140004470(a3) )
  {
    v4 = unknown_libname_18(a1);
    sub_1400044E0(v4, a2);
    return a1 + 4 * a2;
  }
  else
  {
    sub_140001D60(v7, 0x18ui64);
    sub_1400042F0(v7, a1, a4);
    while ( a2 )
    {
      sub_140004410((__int64)v7, (__int64)a3);
      --a2;
    }
    v6 = sub_1400042A0(v7);
    sub_1400042C0(v7);
    return v6;
  }
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);
// 1400040A0: using guessed type _QWORD var_30[3];

//----- (0000000140004180) ----------------------------------------------------
unsigned __int64 __fastcall sub_140004180(unsigned __int64 a1, __int64 a2)
{
  void *v3; // [rsp+20h] [rbp-28h]

  if ( a1 + 39 <= a1 )
    sub_1400019B0(a1, a2);
  v3 = sub_140001A70(a1 + 39);
  if ( !v3 )
    invalid_parameter_noinfo_noreturn();
  *(_QWORD *)((((unsigned __int64)v3 + 39) & 0xFFFFFFFFFFFFFFE0ui64) - 8) = v3;
  return ((unsigned __int64)v3 + 39) & 0xFFFFFFFFFFFFFFE0ui64;
}
// 1400019B0: using guessed type void __fastcall __noreturn sub_1400019B0(_QWORD, _QWORD);

//----- (0000000140004250) ----------------------------------------------------
__int64 __fastcall sub_140004250(unsigned __int64 a1, __int64 a2)
{
  if ( a1 > 0x3FFFFFFFFFFFFFFFi64 )
    sub_1400019B0(a1, a2);
  return 4 * a1;
}
// 1400019B0: using guessed type void __fastcall __noreturn sub_1400019B0(_QWORD, _QWORD);

//----- (00000001400042A0) ----------------------------------------------------
__int64 __fastcall sub_1400042A0(_QWORD *a1)
{
  *a1 = a1[1];
  return a1[1];
}

//----- (00000001400042C0) ----------------------------------------------------
__int64 __fastcall sub_1400042C0(_QWORD *a1)
{
  return _castguard_slow_path_check_nop(*a1, a1[1], a1[2]);
}
// 1400035A0: using guessed type __int64 __fastcall _castguard_slow_path_check_nop(_QWORD, _QWORD, _QWORD);

//----- (00000001400042F0) ----------------------------------------------------
_QWORD *__fastcall sub_1400042F0(_QWORD *a1, __int64 a2, __int64 a3)
{
  *a1 = a2;
  a1[1] = a2;
  a1[2] = a3;
  return a1;
}

//----- (0000000140004330) ----------------------------------------------------
_QWORD *__fastcall sub_140004330(_QWORD *a1, __int64 a2, __int64 a3)
{
  *a1 = *(_QWORD *)unknown_libname_18(a3);
  return a1;
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);

//----- (0000000140004370) ----------------------------------------------------
char *__fastcall sub_140004370(__int64 a1, __int64 a2, __int64 a3)
{
  void *Src; // [rsp+20h] [rbp-48h]
  char *v5; // [rsp+30h] [rbp-38h]
  __int64 v6; // [rsp+50h] [rbp-18h]
  __int64 v7; // [rsp+70h] [rbp+8h] BYREF
  __int64 v8; // [rsp+78h] [rbp+10h] BYREF
  __int64 v9; // [rsp+80h] [rbp+18h] BYREF

  v9 = a3;
  v8 = a2;
  v7 = a1;
  Src = (void *)unknown_libname_20(&v7);
  v6 = unknown_libname_20(&v8);
  v5 = (char *)unknown_libname_20(&v9);
  memmove(v5, Src, v6 - (_QWORD)Src);
  return &v5[v6 - (_QWORD)Src];
}
// 1400023C0: using guessed type __int64 __fastcall unknown_libname_20(_QWORD);

//----- (0000000140004410) ----------------------------------------------------
__int64 __fastcall sub_140004410(__int64 a1, __int64 a2)
{
  __int64 v2; // rax
  __int64 result; // rax
  __int64 v4; // [rsp+20h] [rbp-18h]

  v4 = unknown_libname_18(a2);
  v2 = unknown_libname_18(*(_QWORD *)(a1 + 8));
  sub_140004520(*(_QWORD *)(a1 + 16), v2, v4);
  result = *(_QWORD *)(a1 + 8) + 4i64;
  *(_QWORD *)(a1 + 8) = result;
  return result;
}
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);

//----- (0000000140004470) ----------------------------------------------------
_BOOL8 __fastcall sub_140004470(const void *a1)
{
  int Buf2; // [rsp+24h] [rbp-14h] BYREF

  Buf2 = 0;
  return memcmp(a1, &Buf2, 4ui64) == 0;
}

//----- (00000001400044E0) ----------------------------------------------------
__int64 __fastcall sub_1400044E0(__int64 a1, __int64 a2)
{
  void *v2; // rdi
  __int64 result; // rax
  unsigned __int64 v4; // [rsp+20h] [rbp-18h]
  __int64 v5; // [rsp+40h] [rbp+8h] BYREF
  __int64 v6; // [rsp+48h] [rbp+10h]

  v6 = a2;
  v5 = a1;
  v4 = 4 * a2;
  v2 = (void *)unknown_libname_20(&v5);
  result = 0i64;
  memset(v2, 0, v4);
  return result;
}
// 1400023C0: using guessed type __int64 __fastcall unknown_libname_20(_QWORD);

//----- (0000000140004520) ----------------------------------------------------
__int64 __fastcall sub_140004520(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // rax
  __int64 result; // rax
  _DWORD *v5; // [rsp+20h] [rbp-18h]

  v3 = unknown_libname_18(a2);
  v5 = (_DWORD *)unknown_libname_17(4i64, v3);
  result = *(unsigned int *)unknown_libname_18(a3);
  *v5 = result;
  return result;
}
// 140001700: using guessed type __int64 __fastcall unknown_libname_17(_QWORD, _QWORD);
// 140002280: using guessed type __int64 __fastcall unknown_libname_18(_QWORD);

//----- (0000000140004864) ----------------------------------------------------
_QWORD *__fastcall sub_140004864(_QWORD *a1, char a2)
{
  *a1 = &type_info::`vftable';
  if ( (a2 & 1) != 0 )
    j_j_free(a1);
  return a1;
}
// 1400063A8: using guessed type void *type_info::`vftable';

//----- (0000000140004C84) ----------------------------------------------------
_QWORD *__fastcall sub_140004C84(_QWORD *a1)
{
  a1[2] = 0i64;
  a1[1] = "bad allocation";
  *a1 = &std::bad_alloc::`vftable';
  return a1;
}
// 1400063E0: using guessed type void *std::bad_alloc::`vftable';

//----- (0000000140004CA4) ----------------------------------------------------
void __noreturn sub_140004CA4()
{
  _QWORD pExceptionObject[5]; // [rsp+20h] [rbp-28h] BYREF

  sub_140004C84(pExceptionObject);
  CxxThrowException(pExceptionObject, (_ThrowInfo *)&_TI2_AVbad_alloc_std__);
}
// 140004CA4: using guessed type void __fastcall __noreturn sub_140004CA4();
// 140004CA4: using guessed type _QWORD pExceptionObject[5];

//----- (0000000140004CC4) ----------------------------------------------------
void __noreturn sub_140004CC4()
{
  char pExceptionObject[40]; // [rsp+20h] [rbp-28h] BYREF

  std::bad_array_new_length::bad_array_new_length((std::bad_array_new_length *)pExceptionObject);
  CxxThrowException(pExceptionObject, (_ThrowInfo *)&_TI3_AVbad_array_new_length_std__);
}
// 140004CC4: using guessed type void __fastcall __noreturn sub_140004CC4();

//----- (0000000140004CE4) ----------------------------------------------------
__int64 sub_140004CE4()
{
  int v5; // r11d
  int v6; // r9d
  int v7; // esi
  int v9; // r10d
  int v14; // edi
  int v15; // eax
  unsigned __int64 v16; // rax
  __int64 v17; // rcx
  int v18; // r8d
  int v23; // eax
  char v25; // [rsp+20h] [rbp+8h]

  _RAX = 0i64;
  __asm { cpuid }
  v5 = 0;
  v6 = _RBX;
  v7 = _RAX;
  _RAX = 1i64;
  v9 = _RCX ^ 0x6C65746E | _RDX ^ 0x49656E69;
  __asm { cpuid }
  v14 = _RCX;
  if ( !(v6 ^ 0x756E6547 | v9)
    && ((qword_140009028 = -1i64, v15 = _RAX & 0xFFF3FF0, qword_140009020 = 0x8000i64, v15 == 67264)
     || v15 == 132704
     || v15 == 132720
     || (v16 = (unsigned int)(v15 - 198224), (unsigned int)v16 <= 0x20) && (v17 = 0x100010001i64, _bittest64(&v17, v16))) )
  {
    v18 = dword_1400096E0 | 1;
    dword_1400096E0 |= 1u;
  }
  else
  {
    v18 = dword_1400096E0;
  }
  _RAX = 7i64;
  if ( v7 >= 7 )
  {
    __asm { cpuid }
    v5 = _RBX;
    if ( (_RBX & 0x200) != 0 )
      dword_1400096E0 = v18 | 2;
  }
  dword_140009018 = 1;
  dword_14000901C = 2;
  if ( (v14 & 0x100000) != 0 )
  {
    dword_140009018 = 2;
    dword_14000901C = 6;
    if ( (v14 & 0x8000000) != 0 && (v14 & 0x10000000) != 0 )
    {
      __asm { xgetbv }
      v25 = _RAX;
      if ( (_RAX & 6) == 6 )
      {
        v23 = dword_14000901C | 8;
        dword_140009018 = 3;
        dword_14000901C |= 8u;
        if ( (v5 & 0x20) != 0 )
        {
          dword_140009018 = 5;
          dword_14000901C = v23 | 0x20;
          if ( (v5 & 0xD0030000) == -805109760 && (v25 & 0xE0) == 0xE0 )
          {
            dword_14000901C |= 0x40u;
            dword_140009018 = 6;
          }
        }
      }
    }
  }
  return 0i64;
}
// 140004CE4: using guessed type __int64 __fastcall sub_140004CE4();
// 140009018: using guessed type int dword_140009018;
// 14000901C: using guessed type int dword_14000901C;
// 140009020: using guessed type __int64 qword_140009020;
// 140009028: using guessed type __int64 qword_140009028;
// 1400096E0: using guessed type int dword_1400096E0;

//----- (0000000140004EA4) ----------------------------------------------------
void sub_140004EA4()
{
  dword_1400096E4 = 0;
}
// 1400096E4: using guessed type int dword_1400096E4;

//----- (0000000140005000) ----------------------------------------------------
__int64 __fastcall UserMathErrorFunction(struct _exception *a1)
{
  return 0i64;
}

//----- (0000000140005004) ----------------------------------------------------
bool sub_140005004()
{
  HMODULE ModuleHandleW; // rax
  char *v1; // rcx
  bool result; // al

  ModuleHandleW = GetModuleHandleW(0i64);
  result = ModuleHandleW
        && *(_WORD *)ModuleHandleW == 23117
        && (v1 = (char *)ModuleHandleW + *((int *)ModuleHandleW + 15), *(_DWORD *)v1 == 17744)
        && *((_WORD *)v1 + 12) == 523
        && *((_DWORD *)v1 + 33) > 0xEu
        && *((_DWORD *)v1 + 62) != 0;
  return result;
}

//----- (0000000140005180) ----------------------------------------------------
void sub_140005180()
{
  InitializeSListHead(&stru_1400096F0);
}
// 1400096F0: using guessed type union _SLIST_HEADER stru_1400096F0;

//----- (0000000140005190) ----------------------------------------------------
char sub_140005190()
{
  return 1;
}

//----- (0000000140005194) ----------------------------------------------------
void *sub_140005194()
{
  return &unk_140009700;
}

//----- (000000014000519C) ----------------------------------------------------
void *sub_14000519C()
{
  return &unk_140009708;
}

//----- (00000001400051CC) ----------------------------------------------------
void *sub_1400051CC()
{
  return &unk_140009798;
}

//----- (00000001400051D4) ----------------------------------------------------
void *sub_1400051D4()
{
  return &unk_140009790;
}

//----- (00000001400051DC) ----------------------------------------------------
void sub_1400051DC()
{
  void (**i)(void); // rbx

  for ( i = qword_140006D70; i < qword_140006D70; ++i )
  {
    if ( *i )
      (*i)();
  }
}
// 140006D70: using guessed type void (*qword_140006D70[2])(void);

//----- (0000000140005218) ----------------------------------------------------
void __fastcall sub_140005218()
{
  void (**i)(void); // rbx

  for ( i = &qword_140006D80; i < &qword_140006D80; ++i )
  {
    if ( *i )
      (*i)();
  }
}
// 140006D80: using guessed type void (*qword_140006D80)(void);

//----- (0000000140005690) ----------------------------------------------------
void __fastcall sub_140005690()
{
  std::string::~string(&password);
}
// 1400022D0: using guessed type __int64 __fastcall std::string::~string(_QWORD);

//----- (00000001400056B0) ----------------------------------------------------
void __fastcall sub_1400056B0()
{
  sub_140002190(input_1);
}
// 140009730: using guessed type _QWORD input_1[3];

//----- (00000001400056D0) ----------------------------------------------------
void __fastcall sub_1400056D0()
{
  sub_140002190(qword_140009748);
}
// 140009748: using guessed type __int64 qword_140009748[3];

//----- (00000001400056F0) ----------------------------------------------------
void __fastcall sub_1400056F0()
{
  sub_140002190(qword_140009718);
}
// 140009718: using guessed type __int64 qword_140009718[3];

// nfuncs=220 queued=110 decompiled=110 lumina nreq=0 worse=0 better=0
// ALL OK, 110 function(s) have been successfully decompiled
